# Generated by Django 2.2 on 2019-04-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Project',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=40, verbose_name='项目名称')),
				('describe', models.TextField(default='', verbose_name='描述')),
				('status', models.BooleanField(default=1, verbose_name='状态')),
				('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
				('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
			],
			options={
				'verbose_name': '项目信息',
				'verbose_name_plural': '项目信息',
			},
		),
		migrations.CreateModel(
			name='Module',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=50, verbose_name='模块名称')),
				('describe', models.TextField(default='', verbose_name='描述')),
				('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
				('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Project')),
			],
			options={
				'verbose_name': '模块信息',
				'verbose_name_plural': '模块信息',
			},
		),
	]
