# Generated by Django 2.2 on 2019-04-10 21:14

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('personal', '0001_initial'),
	]

	operations = [
		migrations.AlterModelOptions(
			name='module',
			options={'verbose_name': '模块管理', 'verbose_name_plural': '模块管理'},
		),
		migrations.AlterModelOptions(
			name='project',
			options={'verbose_name': '项目管理', 'verbose_name_plural': '项目管理'},
		),
	]
