# Generated by Django 2.2.1 on 2019-06-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnittestScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(verbose_name='用户id')),
                ('username', models.CharField(default=None, max_length=10, verbose_name='用户名')),
                ('scriptname', models.CharField(max_length=50, verbose_name='脚本名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('py_file', models.FileField(upload_to='')),
                ('del_status', models.IntegerField(default=0, verbose_name='是否删除')),
                ('test_result', models.BooleanField(default=True, verbose_name='测试结果')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
            ],
            options={
                'verbose_name': 'py_unittest管理',
                'verbose_name_plural': 'py_unittest管理',
            },
        ),
    ]
