# Generated by Django 2.2.1 on 2019-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyunitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittestscript',
            name='uploadfilename',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
