# Generated by Django 2.2.1 on 2019-06-10 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocustScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(verbose_name='用户id')),
                ('scriptname', models.CharField(max_length=50, verbose_name='脚本名称')),
                ('host', models.TextField(verbose_name='host')),
                ('encryption', models.IntegerField(verbose_name='是否加密')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('locustfile', models.FileField(upload_to='')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
            ],
            options={
                'verbose_name': 'LOCUST管理',
                'verbose_name_plural': 'LOCUST管理',
            },
        ),
    ]
