# Generated by Django 2.2.1 on 2019-06-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locustmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locustscript',
            name='username',
            field=models.CharField(default=None, max_length=10, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='locustscript',
            name='host',
            field=models.CharField(max_length=200, verbose_name='host'),
        ),
    ]
