# Generated by Django 2.2.1 on 2019-06-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locustmanager', '0003_locustscript_del_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='locustscript',
            name='slave_num',
            field=models.IntegerField(default=0, verbose_name='slave数量'),
        ),
    ]
